#!/bin/bash
python cleartfs.py
rm -r jobs
rm -r output
rm -r tf_states
rm -r jobfiles
rm best_job_and_result.txt
rm chooser.GPEIOptChooser.pkl
rm chooser.GPEIOptChooser_hyperparameters.txt
rm expt-grid.pkl
rm expt-grid.pkl.lock
rm trace.csv
rm spearmint.chooser.GPEIOptChooser.pkl
rm spearmint.chooser.GPEIOptChooser.pkl.lock
rm spearmint.chooser.GPEIOptChooser_hyperparameters.txt
rm spearmint.chooser.GPEIChooser.pkl
rm spearmint.chooser.GPEIChooser.pkl.lock
rm spearmint.chooser.GPEIChooser_hyperparameters.txt
